<?php

namespace frontend\widgets;
use common\models\Diff;
use yii\base\Widget;

class bottomWidgets extends Widget{

    public function init()
    {
        parent::init(); 
    }


    public function run()
    {
      $anons_all = Diff::find()->limit(4)->limit(6)->all();
      return $this->render('_bottom', ['anons_all' => $anons_all]); // TODO: Change the autogenerated stub
    }
}