<?php
/**
 * Created by PhpStorm.
 * User: User
 * Date: 03.09.2017
 * Time: 17:10
 */

namespace frontend\widgets;
use common\models\Categories;
use common\models\Info;
use common\models\Menu;
use common\models\News;
use yii\base\Widget;


class footerWidgets extends Widget{


    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        $menu_model = \common\models\Menu::find()->all();
        return $this->render('_footer', compact('menu_model'));
    }

}