<?php


namespace frontend\widgets;

use common\models\Menu;
use yii\base\Widget;


class navWidgets extends Widget{


    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        $menu = Menu::find()->all();
        $cats = \common\models\Cat::find()->limit('6')->all();
        $reklama = new \common\models\Reklama();
        $allbanner = $reklama->find()->orderBy(['create_at' => SORT_DESC])->where(['type' => 'banner'])->all();
        $slide_news = \common\models\News::find()->orderBy(['create_at' => SORT_DESC])->where(['status' => 1])->all();
        return $this->render('_navbar', compact('slide_news', 'allbanner', 'reklama', 'cats', 'menu'));
    }
}