<?php

namespace frontend\widgets;
use common\models\Article;
use common\models\Follow;
use common\models\News;
use common\models\Reklama;
use yii\base\Widget;

class sideWidgets extends Widget{

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }


    public function run()
    {

        $querydd= \Yii::$app->db->createCommand("SELECT COUNT(*) AS post_id, `post_id` FROM `view_post` GROUP BY `post_id` ORDER BY `post_id` DESC LIMIT 5");
        $licenses = $querydd->queryAll();
        foreach ($licenses as $view){
            $news1 = News::find()->where(['id' => $view['post_id']])->limit('5')->all();
            foreach ($news1 as $popular){
                $newslist[] = $popular;
            }
        }

        $reklama = new Reklama();
        $follow = Follow::find()->limit('6')->all();
        $articles = News::find()->where(['type_cat'=>2])->limit('3')->orderBy(['create_at' => SORT_DESC])->all();

      return $this->render('_sidebar', ['news' => $newslist, 'articles' => $articles, 'reklama' => $reklama, 'follow' => $follow]); // TODO: Change the autogenerated stub
    }
}